from fastapi import FastAPI, Depends, HTTPException
from sqlalchemy.orm import Session
from fastapi.middleware.cors import CORSMiddleware
import models
from database import engine, get_db
from pydantic import BaseModel

models.Base.metadata.create_all(bind=engine)

app = FastAPI()

# Allow CORS from our Next.js frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:3000",
        "http://localhost:3001",
        "https://ai-trip-planner-jet-eight.vercel.app"
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class TripRequest(BaseModel):
    destination: str
    days: int
    budget: str
    companions: str
    interests: str

from agents import trip_orchestrator

@app.get("/")
def read_root():
    return {"message": "FastAPI Orchestrator is running"}

@app.post("/api/generate-trip")
def generate_trip(request: TripRequest, db: Session = Depends(get_db)):
    # Initialize state for LangGraph
    initial_state = {
        "destination": request.destination,
        "days": request.days,
        "budget": request.budget,
        "companions": request.companions,
        "interests": request.interests,
        "weather_info": "",
        "flight_info": "",
        "hotel_info": "",
        "final_itinerary": {}
    }
    
    # Run the graph
    result = trip_orchestrator.invoke(initial_state)
    
    # Return the final JSON generated by the Itinerary Agent
    return result.get("final_itinerary", {"error": "Graph failed to generate itinerary"})
