from fastapi import FastAPI, Depends, HTTPException
from sqlalchemy.orm import Session
from fastapi.middleware.cors import CORSMiddleware
import models
from database import engine, get_db
from pydantic import BaseModel

models.Base.metadata.create_all(bind=engine)

app = FastAPI()

# Allow CORS from our Next.js frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:3000",
        "http://localhost:3001",
        "https://ai-trip-planner-jet-eight.vercel.app"
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class TripRequest(BaseModel):
    destination: str
    source: str
    check_in: str
    check_out: str
    budget: str
    companions: str
    interests: str

from agents import trip_orchestrator

@app.get("/")
def read_root():
    return {"message": "FastAPI Orchestrator is running"}

import traceback
from datetime import datetime

@app.post("/api/generate-trip")
def generate_trip(request: TripRequest, db: Session = Depends(get_db)):
    try:
        # Dynamically calculate days
        d1 = datetime.strptime(request.check_in, "%Y-%m-%d")
        d2 = datetime.strptime(request.check_out, "%Y-%m-%d")
        days = max(1, (d2 - d1).days)
        
        # Initialize state for LangGraph
        initial_state = {
            "destination": request.destination,
            "source": request.source,
            "check_in": request.check_in,
            "check_out": request.check_out,
            "days": days,
            "budget": request.budget,
            "companions": request.companions,
            "interests": request.interests,
            "weather_info": "",
            "flight_info": "",
            "hotel_info": "",
            "flights_list": [],
            "hotels_list": [],
            "final_itinerary": {}
        }
        
        # Run the graph
        result = trip_orchestrator.invoke(initial_state)
        
        # Return the final JSON generated by the Itinerary Agent combined with rich options
        final_itinerary = result.get("final_itinerary", {})
        if "error" not in final_itinerary:
            final_itinerary["flights"] = result.get("flights_list", [])
            final_itinerary["hotels"] = result.get("hotels_list", [])
            final_itinerary["weather"] = result.get("weather_info", "")
        return final_itinerary
    except Exception as e:
        tb = traceback.format_exc()
        return {"error": str(e), "traceback": tb}

import json
from agents import llm
from langchain_core.messages import SystemMessage, HumanMessage

class RecalculateRequest(BaseModel):
    current_itinerary: dict
    instruction: str

@app.post("/api/recalculate-trip")
def recalculate_trip(request: RecalculateRequest):
    try:
        prompt = f"""
        You are an expert travel agent. Modify the following travel itinerary based on the user's instruction.
        
        Current Itinerary:
        {json.dumps(request.current_itinerary)}
        
        User Instruction:
        "{request.instruction}"
        
        Keep all unchanged parts identical, but recompute costs, swaps, or timeline details as requested.
        Respond STRICTLY with the updated valid JSON matching the same structure. Do not include markdown formatting or backticks outside the JSON.
        """
        response = llm.invoke([SystemMessage(content="You are a strict JSON generator."), HumanMessage(content=prompt)])
        text = response.content.replace('```json', '').replace('```', '').strip()
        
        try:
            updated_json = json.loads(text)
        except Exception:
            # Try to scrub formatting
            if "{" in text:
                text_clean = text[text.find("{"):text.rfind("}")+1]
                updated_json = json.loads(text_clean)
            else:
                updated_json = {"error": "Failed to parse updated itinerary", "raw": text}
            
        # Re-attach flights/hotels/weather if missing in updated
        if "flights" not in updated_json and "flights" in request.current_itinerary:
            updated_json["flights"] = request.current_itinerary["flights"]
        if "hotels" not in updated_json and "hotels" in request.current_itinerary:
            updated_json["hotels"] = request.current_itinerary["hotels"]
        if "weather" not in updated_json and "weather" in request.current_itinerary:
            updated_json["weather"] = request.current_itinerary["weather"]
            
        return updated_json
    except Exception as e:
        return {"error": str(e)}
